name: Release Template Tarball

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create template tarball
        run: |
          tar -czf cursor-rules.tar.gz rules README.md

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: cursor-rules.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 